name: Build and Push GenoQuery-API Image

on:
  push:
    branches:
      - main
    paths:
      - 'package/api/**'
  workflow_dispatch:

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Log in to GitHub Container Registry
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Convert repository owner to lowercase
      id: convert-owner
      run: echo "REPO_OWNER=$(echo ${{ github.repository_owner }} | tr '[:upper:]' '[:lower:]')" >> $GITHUB_ENV

    - name: Build and push Docker image
      uses: docker/build-push-action@v4
      with:
        context: ./package/api
        file: ./package/api/dockerfile
        push: true
        tags: |
          ghcr.io/${{ env.REPO_OWNER }}/genoquery-api:latest
          ghcr.io/${{ env.REPO_OWNER }}/genoquery-api:${{ github.sha }}

